[package]
name = "rs-poker-server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
http-body-util = "0.1.0"
tower = { version = "0.5.2", features = ["util"] }
